apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexushr.fullname" . }}-secret
type: Opaque
stringData:
  NEXUSHR_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  NEXUSHR_OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  NEXUSHR_DATABASE_URL: {{ .Values.platform.databaseUrl | quote }}
  NEXUSHR_REDIS_URL: {{ .Values.platform.redisUrl | quote }}
  NEXUSHR_MONGODB_AUDIT_URI: {{ .Values.platform.mongoAuditUri | quote }}
